# Generador de datasets pels plots de Observable

### Importacions

In [3]:
import os
import sys

import pandas as pd

sys.path.append(os.path.abspath("../src"))

from constants import PROCESSED_DATA, OBSERVABLE_DATA
from tool_scripts.geographic_tools import add_cusec_column

### 1r gràfic: CARAC CENSUS TRACT

In [ ]:
df_for_rent_synthetic = pd.read_csv(f"{PROCESSED_DATA}/girona_for_rent_synthetic.csv")
df_for_rent = pd.read_csv(f"{PROCESSED_DATA}/girona_for_rent.csv")

df_all_for_rent = pd.concat(
    [
        df_for_rent_synthetic.drop(columns=["synthetic_id", "year_available"]),
        df_for_rent,
    ],
    ignore_index=True,
)
df_all_for_rent["elevator"] = df_all_for_rent["elevator"].apply(lambda x: 1 if x else 0)
df_all_for_rent.drop(columns=["address", "neighbourhood"], inplace=True) # No es pot fer la mitja de columnes discretes
df_all_for_rent_grouped = df_all_for_rent.groupby('census_tract').mean().reset_index()
print(f"Is census_tract unique? {df_all_for_rent_grouped['census_tract'].is_unique}")
df_all_for_rent_grouped.head(5)

,census_tract,price,area,rooms,floors,elevator,lat,lon
0,1707901001,1228.148855,83.038168,2.517241,2.226923,0.583969,41.983590,2.824905
1,1707901002,1917.142857,99.238095,1.000000,1.050000,0.857143,41.981023,2.826995
2,1707901003,1514.320388,84.388350,2.213592,2.660194,0.708738,41.975914,2.824779
3,1707901004,1649.000000,105.100000,2.700000,3.500000,0.900000,41.975318,2.825222
4,1707902001,916.041667,54.083333,1.375000,2.791667,0.916667,41.981682,2.821350

,census_tract,price,area,rooms,floors,elevator,lat,lon
0,1707901001,1228.148855,83.038168,2.517241,2.226923,0.583969,41.983590,2.824905
1,1707901002,1917.142857,99.238095,1.000000,1.050000,0.857143,41.981023,2.826995
2,1707901003,1514.320388,84.388350,2.213592,2.660194,0.708738,41.975914,2.824779
3,1707901004,1649.000000,105.100000,2.700000,3.500000,0.900000,41.975318,2.825222
4,1707902001,916.041667,54.083333,1.375000,2.791667,0.916667,41.981682,2.821350

In [23]:
df_all_for_rent_grouped.to_csv(f"{OBSERVABLE_DATA}/df_all_for_rent_grouped.csv", index=False)

NameError: name 'OBSERVABLE_DATA' is not defined